[package]
name = "calculator-gtk"
version = "0.1.0"
authors = ["Alik Aslanyan <cplusplus@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
gtk = "0.7.0"
relm = "0.18.0"
relm-derive = "0.18.0"
calculator-engine = { path = "../calculator-engine" }